<a href="https://colab.research.google.com/github/jxy-ygjm/EC1B1-Coursework/blob/main/EC1B1_Code_ipynb_Group_55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EC1B1 Coursework

**Winter Term 2025/2026**

<div style="font-family: system-ui; padding: 20px 30px 20px 20px; background-color: #FFFFFF; border-left: 8px solid #0570b0; border-radius: 8px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);max-width:600px;color:#212121;">

**Coursework Notebook**
- Group 55
    - Xuanyang Ji
    - Felix Kalu
    - Rishi Ganiger
- Date: 28/02/2026

</div>

**Importing libraries**

To run the notebook, we first need to import all the libraries below

In [1]:
import pandas as pd

## Section 1: Importing the Data

In 24/03/2025, International Financial Statistics (IFS) data were organised around topics with indicators accessible via existing datasets in the IMF Data Portal. IMF deleted the "Query" function, so in this Notebook, we download data from different datasets separately.

The raw data are stored on [GitHub](https://github.com/jxy-ygjm/EC1B1-Coursework), allowing easier data import.

We store all the raw data in a dictionary, so we can easily handle procedures like merge

In [2]:
# Raw URL of data
raw_url = (
    "https://raw.githubusercontent.com/jxy-ygjm/EC1B1-Coursework/main/data/raw/"
)

# Specific data name
data_name = [
    "consumer_price", "exchange_rate", "industrial_production",
    "international_reserves"
]

In [3]:
# Create empty dictionary storing data
data = {}

# Read data
for name in data_name:
    data[name] = pd.read_csv(raw_url + name + ".csv")

Now, we try to investigate the dataframes

In [4]:
for value in data.values():
    print(value.columns)

Index(['COUNTRY', 'INDEX_TYPE', 'COICOP_1999', 'TYPE_OF_TRANSFORMATION',
       'FREQUENCY', 'TIME_PERIOD', 'OBS_VALUE', 'SCALE'],
      dtype='object')
Index(['COUNTRY', 'INDICATOR', 'TYPE_OF_TRANSFORMATION', 'FREQUENCY',
       'TIME_PERIOD', 'OBS_VALUE', 'SCALE'],
      dtype='object')
Index(['COUNTRY', 'PRODUCTION_INDEX', 'TYPE_OF_TRANSFORMATION', 'FREQUENCY',
       'TIME_PERIOD', 'OBS_VALUE', 'SCALE'],
      dtype='object')
Index(['COUNTRY', 'INDICATOR', 'UNIT', 'FREQUENCY', 'TIME_PERIOD', 'OBS_VALUE',
       'SCALE'],
      dtype='object')

We can see that only the `TIME_PERIOD` and `OBS_VALUE` are useful to us.

We now try to create a single dataframe for Spain and US

In [5]:
# Set a list for clean Spain data
spain_cleaned = []

for name, df in data.items():
    temp = df[df["COUNTRY"] == "Spain"][["TIME_PERIOD", "OBS_VALUE"]].copy()
    temp = temp.rename(columns={"OBS_VALUE": name})
    spain_cleaned.append(temp)

df_spain = pd.concat(spain_cleaned, axis=1)

In [6]:
# Investigate the dataframe
df_spain.head()

,TIME_PERIOD,consumer_price,TIME_PERIOD,exchange_rate,TIME_PERIOD,industrial_production,TIME_PERIOD,international_reserves
0,1959-M12,2.525752,1959-M12,60.0,1961-M01,18.687510,1959-M12,200.14101
1,1960-M01,2.505928,1960-M01,60.0,1961-M02,18.253463,1960-M01,233.26019
2,1960-M02,2.503895,1960-M02,60.0,1961-M03,18.429428,1960-M02,253.21561
3,1960-M03,2.500846,1960-M03,60.0,1961-M04,18.617124,1960-M03,299.28248
4,1960-M04,2.502879,1960-M04,60.0,1961-M05,19.590799,1960-M04,326.28248

In [7]:
# Set a list for clean US data
us_cleaned = []

for name, df in data.items():
    temp = (
        df[df["COUNTRY"] == "United States"]
        [["TIME_PERIOD", "OBS_VALUE"]]
        .copy()
    )
    temp = temp.rename(columns={"OBS_VALUE": name})
    us_cleaned.append(temp)

df_us = pd.concat(us_cleaned, axis=1)

In [8]:
# Investigate the dataframe
df_us.head()

,TIME_PERIOD,consumer_price,TIME_PERIOD,exchange_rate,TIME_PERIOD,industrial_production,TIME_PERIOD,international_reserves
373,1959-M12,13.482806,NaN,NaN,NaN,NaN,1959-M12,21543.4138
374,1960-M01,13.436946,NaN,NaN,NaN,NaN,1960-M01,21539.3167
375,1960-M02,13.482806,NaN,NaN,NaN,NaN,1960-M02,21445.6179
376,1960-M03,13.482806,NaN,NaN,NaN,NaN,1960-M03,21411.2592
377,1960-M04,13.528666,NaN,NaN,NaN,NaN,1960-M04,21344.4744

As `consumer_price`, `exchange_rate` and `industrial_production` are indices or have direct meaning, we do not need to know their scale, but for international_reserves, as its nominal measure, we need to know its scale

In [9]:
data["international_reserves"]["SCALE"].head()

0    Millions
1    Millions
2    Millions
3    Millions
4    Millions
Name: SCALE, dtype: object

Can see all the data are in Millions scale, we can rename the column to highlight this

In [10]:
df_spain = df_spain.rename(
    columns={"international_reserves": "international_reserves (M)"}
)
df_us = df_us.rename(
    columns={"international_reserves": "international_reserves (M)"}
)

In [13]:
df_spain.head()

,TIME_PERIOD,consumer_price,TIME_PERIOD,exchange_rate,TIME_PERIOD,industrial_production,TIME_PERIOD,international_reserves (M),COUNTRY
0,1959-M12,2.525752,1959-M12,60.0,1961-M01,18.687510,1959-M12,200.14101,Spain
1,1960-M01,2.505928,1960-M01,60.0,1961-M02,18.253463,1960-M01,233.26019,Spain
2,1960-M02,2.503895,1960-M02,60.0,1961-M03,18.429428,1960-M02,253.21561,Spain
3,1960-M03,2.500846,1960-M03,60.0,1961-M04,18.617124,1960-M03,299.28248,Spain
4,1960-M04,2.502879,1960-M04,60.0,1961-M05,19.590799,1960-M04,326.28248,Spain

## Section 2: Cleaning the Data

In [11]:
df_spain["COUNTRY"] = "Spain"
df_us["COUNTRY"] = "US"

df = pd.concat([df_spain, df_us], axis=0)

In [12]:
df

,TIME_PERIOD,consumer_price,TIME_PERIOD,exchange_rate,TIME_PERIOD,industrial_production,TIME_PERIOD,international_reserves (M),COUNTRY
0,1959-M12,2.525752,1959-M12,60.0,1961-M01,18.687510,1959-M12,200.141010,Spain
1,1960-M01,2.505928,1960-M01,60.0,1961-M02,18.253463,1960-M01,233.260190,Spain
2,1960-M02,2.503895,1960-M02,60.0,1961-M03,18.429428,1960-M02,253.215610,Spain
3,1960-M03,2.500846,1960-M03,60.0,1961-M04,18.617124,1960-M03,299.282480,Spain
4,1960-M04,2.502879,1960-M04,60.0,1961-M05,19.590799,1960-M04,326.282480,Spain
...,...,...,...,...,...,...,...,...,...
741,1990-M08,60.351608,NaN,NaN,NaN,NaN,1990-M08,169458.603357,US
742,1990-M09,60.856066,NaN,NaN,NaN,NaN,1990-M09,175533.733633,US
743,1990-M10,61.222946,NaN,NaN,NaN,NaN,1990-M10,170874.784032,US
744,1990-M11,61.360525,NaN,NaN,NaN,NaN,1990-M11,172797.695574,US
745,1990-M12,61.360525,NaN,NaN,NaN,NaN,1990-M12,173093.564608,US